#!/bin/sh

set -e
set -u

xdg_dirs() {
    local dirs home
    eval "dirs=\${XDG_$1_DIRS:-}; home=\${XDG_$1_HOME:-}"
    if [ -n "${dirs:-}" ]; then
        echo "$dirs"
    elif [ -n "${home:-}" ]; then
        echo "$home"
    else
        echo "$HOME/$2"
    fi
}

NAME="${1:-brett}"
HERE="$(dirname "$(readlink -e "$0")")"
export EMACS_SOCKET_NAME="$XDG_RUNTIME_DIR/emacs/$NAME"
export PATH="$PATH:$HERE/.local/bin"
export XDG_CONFIG_DIRS="$HERE/.config:$(xdg_dirs CONFIG .config)"
export XDG_CONFIG_HOME="$HERE/.config"
export XDG_DATA_DIRS="$HERE/data:$(xdg_dirs DATA .local/share)"
export XDG_DATA_HOME="$HERE/data"
export XDG_STATE_DIRS="$HERE/state:$(xdg_dirs STATE .local/state)"
export XDG_STATE_HOME="$HERE/state"
export ZDOTDIR="$XDG_CONFIG_HOME/bcsh"
unset DISPLAY WAYLAND_DISPLAY

if ! SHELL="$(which zsh 2>/dev/null)"; then
    SHELL="$HERE/bcsbash"
fi
export SHELL

mkdir -p --mode=0700 "$XDG_DATA_HOME" "$XDG_STATE_HOME" "$(dirname "$EMACS_SOCKET_NAME")"
umask 077
emacs --daemon="$EMACS_SOCKET_NAME" --no-init-file --load "$XDG_CONFIG_HOME/emacs/init.el"
exec "$HERE/.local/bin/reattach" "$NAME" -c "$HERE/.screenrc"
