#!/bin/bash

_canrun() {
    type "$@" >/dev/null 2>&1
}

_load_systemd_envvars() {
    local envfile="$(mktemp --tmpdir bcsh-XXXXXXXX.env)" || return $?
    systemctl --user show-environment \
        | grep -vE '^(HOME|LANG|LOGNAME|PATH|SHELL|USER|USERNAME)=' >"$envfile" \
        && source "$envfile" \
        && export $(awk '(match($0, "^[A-Z][A-Z0-9_]*=")){print substr($0, 1, RLENGTH - 1)}' "$envfile")
    /bin/rm "$envfile"
}

_tryalias() {
    _canrun "$1" && shift && name="$1" && shift && eval "alias $name='$*'"
}

if [ -d /run/systemd/system ]; then
    _load_systemd_envvars
    trap _load_systemd_envvars USR2
fi

if [ -z "${EDITOR:-}" ]; then
    if EDITOR="$(which emacsclient 2>/dev/null)"; then
        export ALTERNATE_EDITOR="$(which emacs)"
    else
        EDITOR=/bin/nano
    fi
    export EDITOR
fi
export GREP_COLOR="${GREP_COLOR:-1;32}"
export LESS="${LESS:-XRF}"
export PAGER="${PAGER:-/usr/bin/less}"
export PYTHONSTARTUP="${PYTHONSTARTUP:-$HOME/.config/pythonstartup.py}"

b() { ls -Alh --color=always "$@" | $PAGER; }
bsplit() { split -d -b "$1" "$2" "$(basename "$2")."; }
cdr() { cd "$(realpath "${1:-.}")"; }
cwdiff() { wdiff -n "$@" | colordiff | $PAGER; }
reallines() { grep -Ev '^[[:space:]]*($|#)' "$@" | $PAGER; }
stamp() { find "$@" -print0 | xargs -0 touch; }
today() { isodate now; }

if _canrun colordiff; then
    cdiff() {
        local last_arg
        eval "last_arg=\$$#"
        if [ -e "$last_arg" ]; then
            colordiff -u "$@"
        else
            colordiff "$@"
        fi
    }
fi

if _canrun csvtool; then
    csvl() {
        csvtool readable "$@" | $PAGER;
    }
fi

d() {
    if [ -z "$1" ]; then
        dirs -p
    elif [ -d "$1" ] || [ - = "$1" ] || [ "${1#+}" != "$1" ]; then
        eval pushd "\"$1\""
    elif [ "${1#-}" != "$1" ]; then
        dirs "$@"
    elif [ -z "${1#[0-9]}" ]; then
        eval pushd "\"+$1\""
    else
        echo "d: not directory or options: $@" >&2
        return 2
    fi
}

isodate() {
    local date_arg
    if [ -z "${1:-}" ] || [ "${1#-}" != "$1" ]; then
        date_arg=now
    else
        date_arg="$1"; shift
    fi
    date --iso-8601=date --date="$date_arg" "$@"
}

pl() {
    local newdir="$(pwd)"
    eval cd - >/dev/null
    eval pushd "\"$newdir\""
}

py() {
    if [ -z "$VIRTUAL_ENV" ] && type python3 >/dev/null 2>&1; then
        python3 "$@"
    else
        python "$@"
    fi
}

str() {
    if file -b "$1" | grep -q text; then
        $PAGER "$1"
    else
        strings -a "$1" | $PAGER
    fi
}

_up() {
    local nextpath
    if [ -z "$2" ]; then
        nextpath=".."
    elif [ -z "${2#[1-9]}" ]; then
        nextpath=""
        for i in $(seq 1 "$2"); do
            nextpath="${nextpath}../"
        done
    else
        nextpath="$(dirname "$(pwd)")"
        while [ "$nextpath" != "/" ]; do
            if basename "$nextpath" | grep -qFi "$2"; then
                break
            fi
            nextpath="$(dirname "$nextpath")"
        done
        if [ "$nextpath" = "/" ]; then
            echo "up: no match found for $2" >&2
            return 1
        fi
    fi
    eval "$1" "$nextpath"
}

if _canrun qrencode; then
    qr() {
        if [ -z "$1" ]; then
            echo "Usage: qr URL" >&2
            return 2
        fi
        fn="$(tempfile -p qr- -s .png)" && \
            qrencode -o "$fn" "$1" && eog "$fn" && rm -f "$fn"
    }
fi

if _canrun svn && _canrun colordiff; then
    svncdiff() {
        local revnum
        if [ $# -ge 1 ] \
               && revnum="${1#[rc]}" \
               && [ "$revnum" -ge 0 ] 2>/dev/null \
               && ! [ -e "$1" ]; then
            shift
            set -- "-c$revnum" "$@"
        fi
        svn diff "$@" | cdiff -dn | $PAGER
    }
fi

if _canrun systemctl; then
    _wrap_systemctl() {
        local cmd="$1"; shift
        local need_root
        if [ "$(id -u)" = 0 ]; then
            need_root=0
        else
            need_root=1
            for arg in "$@"; do
                case "$arg" in
                    --user*)
                        need_root=0
                        break
                        ;;
                esac
            done
        fi
        case "$need_root" in
            1) sudo $cmd "$@" ;;
            *) $cmd "$@" ;;
        esac
    }

    if journalctl -n1 >/dev/null 2>&1; then
        alias jctl=journalctl
    else
        jctl() { _wrap_systemctl journalctl "$@"; }
    fi
    sctl() { _wrap_systemctl systemctl "$@"; }
    alias ujctl='journalctl --user'
    alias usctl='systemctl --user'
fi

vcsfind() {
    find \( -name 'CVS' -o -name '.svn' -o -name '.hg' -o -name '.git' \) \
        -not -prune -o \( "$@" \)
}

wrap() {
    local columns
    if [ "${1:-0}" -gt 0 ] 2>/dev/null; then
        columns="$1"; shift
    else
        columns="${COLUMNS:-80}"
    fi
    fold -sw "$columns" "$@"
}

_tryalias emacs wemacs VISUAL=emacs EDITOR=emacs
_tryalias emacsclient visit emacsclient -n
_tryalias emacsclient wemacsc VISUAL=emacsclient EDITOR=emacsclient
_tryalias ftp ftp ftp -p
_tryalias xdg-open o xdg-open
_tryalias grep cgrep grep --color=always
_tryalias grep vcscgrep grep --color=always -r --exclude-dir={CVS,.svn,.hg,.git}
_tryalias grep vcsgrep grep -r --exclude-dir={CVS,.svn,.hg,.git}
_tryalias ipv6calc rev6 ipv6calc --quiet --out revnibbles.arpa
_tryalias less l less
_tryalias nano wnano VISUAL=nano EDITOR=nano
_tryalias readlink realpath readlink -e
_tryalias shred zeroout shred -n 0 -z
_tryalias trash rm trash
_tryalias xclip xcopy xclip -selection clipboard
_tryalias xclip xpaste xclip -selection clipboard -o
_tryalias xmodmap mx1k xmodmap ~/.config/xmodmap/mx1k
_tryalias xmodmap nomx1k xmodmap -e '"pointer = default"'
_tryalias youtube-dl ydl youtube-dl --prefer-free-formats \
          --output '"%(autonumber)s-%(title)s.%(ext)s"'

echo -n $PATH | tr : \\0 | xargs -0 ls -1p 2>/dev/null \
      | grep -E '^python[1-9][.0-9]*$' | while read pybin; do
    _tryalias "$pybin" "py${pybin#python}" "$pybin"
done
unset pybin

alias cp='cp -i'
alias mv='mv -i'
alias noproxy='http_proxy=""'
alias pd=popd
alias pip='py -m pip'
alias pydoc='py -m pydoc'
alias rrm=/bin/rm
alias up='_up cd'
alias upp='_up pushd'
alias venv='py -m venv'

_canrun reattach || _tryalias screen reattach screen -dR
_canrun x || alias x='dtrx'
[ -e "/usr/share/doc/mutt/manual.txt.gz" ] && \
    alias muttman='zless /usr/share/doc/mutt/manual.txt.gz'

if python3 -m markdown --version >/dev/null 2>&1; then
    alias _pymarkdown='python3 -m markdown -x sane_lists -x tables'
    alias markdown='_pymarkdown'
    alias sm='_pymarkdown -x smarty'
elif _canrun smartypants && _canrun markdown; then
    sm() {
        smartypants --attr qbdeu "$@" | markdown
    }
fi

[ -e "$ZDOTDIR/local" ] && source "$ZDOTDIR/local"
unset _canrun _tryalias
